### ISSUE TITLE
Using MiniIE as a service

### ISSUE THREAD

**Issue by pminervini** [gkiril/minie#1]
Hello,
Is there anything out there for exposing/using MiniIE as a service?

**Comment by gkiril** [comment]
This is all there is :) 
You can use the class `Main.java` to build an executable jar though. 
Hope this helps.

**Comment by pminervini** [comment]
Thanks! Let me work a bit on this - it would be great to contribute :)

**Comment by gkiril** [comment]
I am glad you like it; collaboration is always welcomed ;)

**Comment by pminervini** [comment]
Done!

I can also for the `minie` repository, commit the code for the service, and do a pull request if that works for you

**Comment by gkiril** [comment]
Nice, please do! BTW, please put in `gitignore` the folders `target` and `.idea` (no need for those to be in the code). 
Quick question: did you change something inside of MinIE code, or all the changes that you made are just the classes written in `uk/ac/ucl/cs/mr`?

**Comment by pminervini** [comment]
> Nice, please do! BTW, please put in gitignore the folders target and .idea (no need for those to be in the code).

Done!

> Quick question: did you change something inside of MinIE code, or all the changes that you made are just the classes written in uk/ac/ucl/cs/mr?

My code is just the classes in `uk/ac/ucl/cs/mr`.

**Comment by gkiril** [comment]
Awesome! Could you then commit your package `uk/ac/ucl/cs/mr`?

**Comment by joselpart** [comment]
Hi, I just cloned the repo and was trying to test it using it as a service but I am getting the following error:

[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building minie 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ minie ---
[INFO] Deleting /home/jose-trusty/Software/nlp_tools/minie/target
[INFO] 
[INFO] --- maven-resources-plugin:2.3:resources (default-resources) @ minie ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 26 resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.0.2:compile (default-compile) @ minie ---
[INFO] Compiling 54 source files to /home/jose-trusty/Software/nlp_tools/minie/target/classes
[INFO] 
[INFO] --- exec-maven-plugin:1.6.0:java (default-cli) @ minie ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.924s
[INFO] Finished at: Tue Mar 27 15:11:20 BST 2018
[INFO] Final Memory: 29M/612M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:java (default-cli) on project minie: The parameters 'mainClass' for goal org.codehaus.mojo:exec-maven-plugin:1.6.0:java are missing or invalid -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginParameterException

I checked the pom file and the mainClass parameter seems to be correctly specified. Do you have any idea what may be the problem?

**Comment by pminervini** [comment]
@joselpart Hi! This should do the work:

```bash
$ mvn clean compile exec:java -Dexec.mainClass="uk.ac.ucl.cs.mr.Main"
[..]
[INFO] --- exec-maven-plugin:1.6.0:java (default-cli) @ minie ---
MinIE Service
Mar 27, 2018 3:26:08 PM org.glassfish.grizzly.http.server.NetworkListener start
INFO: Started listener bound to [localhost:8080]
Mar 27, 2018 3:26:09 PM org.glassfish.grizzly.http.server.HttpServer start
INFO: [HttpServer] Started.
Application started.
Stop the application using CTRL+C
```
